import { IBook } from 'src/app/types/book';

export const detective: IBook[] = [
  {
    id: 1,
    image: 'assets/Images/detective/AStudyInScarlet.jpg',
    rate: 5,
    title: 'Sherlok Holmes A Study in Scarlet',
    author: 'Arthur Conan Doyle',
    inStock: true,
    price: 20,
    jenre: 'Detective',
    details: {
      pages: 125,
      yearOfPublication: 2020,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 2,
    image: 'assets/Images/detective/PerilatEndHouse.jpg',
    rate: 4,
    title: 'Peril at End House',
    author: 'Agatha Christie',
    inStock: false,
    price: 25.3,
    jenre: 'Detective',
    details: {
      pages: 256,
      yearOfPublication: 2019,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 3,
    image: 'assets/Images//detective/DeathIsaLonelyBusiness.jpg',
    rate: 3,
    title: 'Death Is a Lonely Business',
    author: 'Ray Bradbury',
    inStock: false,
    price: 30,
    jenre: 'Detective',
    details: {
      pages: 311,
      yearOfPublication: 2017,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 4,
    image: 'assets/Images/detective/TheBlackDahlia.jpg',
    rate: 4,
    title: 'The Black Dahlia',
    author: 'James Ellroy',
    inStock: true,
    price: 27.5,
    jenre: 'Detective',
    details: {
      pages: 523,
      yearOfPublication: 2021,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 5,
    image: 'assets/Images/detective/TheMurdersintheRueMorgue.jpg',
    rate: 5,
    title: 'The Murders in the Rue Morgue',
    author: 'Edgar Allan Poe',
    inStock: true,
    price: 21.2,
    jenre: 'Detective',
    details: {
      pages: 456,
      yearOfPublication: 2022,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 6,
    image: 'assets/Images/detective/Thenameoftherose.jpg',
    rate: 3,
    title: 'The name of the rose',
    author: 'Umberto Eco',
    inStock: false,
    price: 19.3,
    jenre: 'Detective',
    details: {
      pages: 370,
      yearOfPublication: 2016,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 7,
    image: "assets/Images/detective/Akiller'smind.jpg",
    rate: 4,
    title: "A killer's mind",
    author: 'Mike Omer',
    inStock: true,
    price: 23.6,
    jenre: 'Detective',
    details: {
      pages: 576,
      yearOfPublication: 2021,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 8,
    image: 'assets/Images/detective/Thegirlonthetrain.jpg',
    rate: 4,
    title: 'The girl on the train',
    author: 'Paula Hawkins',
    inStock: true,
    price: 30.1,
    jenre: 'Detective',
    details: {
      pages: 603,
      yearOfPublication: 2018,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 9,
    image: 'assets/Images/detective/TheSecretofFatherBrown.jpg',
    rate: 4,
    title: 'The Secret of Father Brown',
    author: 'Gilbert Keith Chesterton',
    inStock: false,
    price: 17.9,
    jenre: 'Detective',
    details: {
      pages: 468,
      yearOfPublication: 2021,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
];
