import { IBook } from "src/app/types/book";

export const horror: IBook[] = [
  {
    id: 1,
    image: 'assets/Images/',
    rate: 4,
    title: 'The Stand',
    author: 'Stephen King',
    inStock: true,
    price: 20,
    jenre: 'Horror',
    details: {
      pages: 408,
      yearOfPublication: 2022,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 2,
    image: 'assets/Images/',
    rate: 4,
    title: 'Night over water',
    author: 'Ken Follett',
    inStock: false,
    price: 25.3,
    jenre: 'Horror',
    details: {
      pages: 378,
      yearOfPublication: 2021,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 3,
    image: 'assets/Images/',
    rate: 5,
    title: 'Bow Before the Elf Queen',
    author: 'J.M. Kearl',
    inStock: false,
    price: 30,
    jenre: 'Horror',
    details: {
      pages: 345,
      yearOfPublication: 2018,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 4,
    image: 'assets/Images/',
    rate: 5,
    title: 'The Shining',
    author: 'Stephen King',
    inStock: true,
    price: 27.5,
    jenre: 'Horror',
    details: {
      pages: 535,
      yearOfPublication: 2019,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  },
  {
    id: 5,
    image: 'assets/Images/',
    rate: 3,
    title: 'Mexican Gothic',
    author: 'Silvia Moreno-Garcia',
    inStock: true,
    price: 20.2,
    jenre: 'Horror',
    details: {
      pages: 401,
      yearOfPublication: 2021,
      cover: 'Hardcover',
      language: 'English',
      description: '',
    },
  }
]
